# Generated by Django 2.1.2 on 2018-11-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(default='open_text', max_length=20)),
                ('q_text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(default='open_text', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='survey_title', max_length=20)),
                ('cat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('no_stars', models.PositiveIntegerField(default=0)),
                ('no_surveys', models.PositiveIntegerField(default=0)),
                ('t_contributed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_text', models.CharField(default=None, max_length=200)),
                ('s_q', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyQuestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.User')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='r_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.ResponseType'),
        ),
    ]
