# Generated by Django 2.1.3 on 2018-11-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20181109_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.User'),
        ),
    ]
