# Generated by Django 2.1.3 on 2018-11-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='response',
        ),
    ]
