# Generated by Django 2.1.3 on 2018-11-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20181110_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestions',
            old_name='surveyId',
            new_name='survey',
        ),
    ]
