# Generated by Django 2.1.2 on 2018-11-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20181110_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='survey',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyQuestions'),
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='response',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
